image: openjdk:8u242-jdk
#image: adoptopenjdk:13.0.2_8-jdk-openj9-0.18.0-bionic
#        -Dpermit.jdk9.builds=true

variables:
  OPTS: >
        -quiet
        -Djavac.compilerargs=-nowarn
        -Dbuild.compiler.deprecation=false
        -Dcluster.config=streamsim
        -Dreleasejson=../netbeansrelease.json
        -Dmetabuild.branch=release113-streamsim

before_script:
  - apt-get -qq update
  - apt-get install ant zip -y
  - wget -q https://download.netbeans.org/netbeans/8.2/final/zip/netbeans-8.2-201609300101-cpp.zip
  - wget -q http://www.java2s.com/Code/JarDownload/jsearch/jsearch-2.0_05.jar.zip

stages:
  - build

build:
  stage: build
  script:
    # build
    - ant $OPTS build
    # remove offending .xml
    - rm nbbuild/netbeans/platform/config/Modules/org-netbeans-libs-batik-read.xml
    # add dlight cluster from NetBeans 8.2
    - unzip -q netbeans-8.2-201609300101-cpp.zip
    - cp -R netbeans/dlight nbbuild/netbeans/
    # add JavaHelp
    - unzip -q jsearch-2.0_05.jar.zip
    - cp jsearch-2.0_05.jar nbbuild/netbeans/harness/antlib/
    # build zip
    - cd nbbuild && zip -r netbeans-release113-streamsim.zip netbeans && cd ..
  artifacts:
      paths:
        - nbbuild/netbeans-release113-streamsim.zip
