image: openjdk:8u242-jdk
#image: adoptopenjdk:13.0.2_8-jdk-openj9-0.18.0-bionic
#        -Dpermit.jdk9.builds=true

variables:
  OPTS: >
        -quiet
        -Djavac.compilerargs=-nowarn
        -Dbuild.compiler.deprecation=false
        -Dcluster.config=streamsim

before_script:
  - apt-get update
  - apt-get -q -y install ant zip
  - wget -q https://download.netbeans.org/netbeans/8.2/final/zip/netbeans-8.2-201609300101-cpp.zip

stages:
  - build

build:
  stage: build
  script:
    # clean and build
    - ant $OPTS clean
    - ant $OPTS build
    # remove offending .xml
    - rm nbbuild/netbeans/platform/config/Modules/org-netbeans-libs-batik-read.xml
    # add dlight cluster from NetBeans 8.2
    - unzip -q netbeans-8.2-201609300101-cpp.zip
    - cp -R netbeans/dlight nbbuild/netbeans/
    # build zip
    - zip -r netbeans.zip nbbuild/netbeans
    - bash -c "ls -l"
    - bash -c "ls -l nbbuild"
  artifacts:
      paths:
        - netbeans.zip
        - nbbuild/netbeans
