image: adoptopenjdk:13.0.2_8-jdk-openj9-0.18.0-bionic

before_script:
  - apt-get update
  - apt-get -y install ant
  - apt-get -y install make mingw-w64

variables:
  - OPTS="-Dcluster.config=streamsim clusters.config.streamsim.list=nb.cluster.harness,nb.cluster.bootstrap,nb.cluster.platform,nb.cluster.ide,nb.cluster.extide,nb.cluster.java -Dpermit.jdk9.builds=true -Ddo.build.windows.launchers=true -quiet -Djavac.compilerargs=-nowarn -Dbuild.compiler.deprecation=false"

stages:
  - build

build:
  stage: build
  before_script:
    - ant $OPTS clean
  script:
    - ant $OPTS build-no-zip
    - ant $OPTS test -Dtest.includes=NoTestsJustBuild
  artifacts:
      paths:
        - nbbuild/netbeans
